from __future__ import annotations

import datetime
import sys
from pathlib import Path

README_NAME = "README.md"


def resolve_target_dir(args: list[str]) -> Path:
    if not args:
        return Path.cwd()

    raw = Path(args[0]).expanduser()
    if raw.is_dir():
        return raw
    if raw.exists():
        return raw.parent

    # If path does not exist, treat it as a directory candidate.
    return raw


def build_readme_content(target_dir: Path) -> str:
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    return (
        "# README\n\n"
        f"Generated by OmniIsle at {now}.\n\n"
        "## Notes\n"
        "- This file was created from the Windows context menu.\n"
        f"- Target directory: {target_dir}\n"
    )


def main() -> int:
    target_dir = resolve_target_dir(sys.argv[1:]).resolve()
    target_dir.mkdir(parents=True, exist_ok=True)

    readme_path = target_dir / README_NAME
    if readme_path.exists():
        print(f"已存在: {readme_path}")
        return 0

    readme_path.write_text(build_readme_content(target_dir), encoding="utf-8")
    print(f"已创建: {readme_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
